services:
  gesturesensor:
    container_name: gesturesensor
    restart: unless-stopped
    image: gesturesensor:latest
    environment:
      - TZ=Asia/Ho_Chi_Minh  # Timezone cho Việt Nam
    volumes:
      - ./config.yml:/code/config.yml:ro
